# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.runs/synth_1/top_fpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.cache/wt [current_project]
set_property parent.project_path /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_output_repo /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/openMSP430_defines.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/uart_defines.v}
}
set_property file_type "Verilog Header" [get_files {{/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/openMSP430_defines.v}}]
set_property file_type "Verilog Header" [get_files {{/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/uart_defines.v}}]
read_verilog -library xil_defaultlib {
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/openmsp430_copy/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/bootchip.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/clock_top.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/verilog_c2s/mem_data.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/verilog_c2s/mem_prog.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/memchk.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/mux.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_alu.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_and_gate.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_clock_gate.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_clock_module.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_dbg.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_dbg_uart.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_execution_unit.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_frontend.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/periph/omsp_gpio.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_mem_backbone.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_multiplier.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_register_file.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_scan_mux.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_sfr.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_sync_cell.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_sync_reset.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_wakeup_cell.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/omsp_watchdog.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_openmsp430/openMSP430.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/pwm.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/raminfr.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/raminfrRx.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/rs485.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/secded_d.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/secded_p.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/top.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/openmsp430_copy/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/chip_fpga/chip_fpga.srcs/sources_1/imports/suresh/Desktop/top_digital_fpga.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/uart_receiver.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/uart_regs.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/uart_rfifo.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/uart_sync_flops.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/uart_tfifo.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/omsp430_ZYBO_10/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/c2s-iisc-rc-team-c2s-iisc-b2c0ebac54aa/C2S_v2/Design_files/digital/rtl/verilog_c2s/uart-rs485/uart_transmitter.v}
  {/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/imports/IIsc files/openmsp430_copy/omsp430_ZYBO_10.srcs/sources_1/imports/Priya/chip_fpga/chip_fpga.srcs/sources_1/imports/suresh/Desktop/top_fpga.v}
}
read_ip -quiet /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]

read_ip -quiet /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/constrs_1/imports/IIsc files/ZYBO.xdc}}
set_property used_in_implementation false [get_files {{/home/iisclap/Downloads/FPGA_10NOV/FPGA_10NOV.srcs/constrs_1/imports/IIsc files/ZYBO.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_fpga -part xc7z010clg400-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_fpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_fpga_utilization_synth.rpt -pb top_fpga_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
