`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: IISc
// Engineer: Devanjan Maiti (devanjan@dese.iisc.ernet.in)
//           Mudasir Mir    (mudasir.mir7@gmail.com)
// 
// Create Date: 17.05.2017 11:52:35
// Design Name: 
// Module Name: temp_sensor_top
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: Top Level Module of the digital Front-End  for C2S56001 on-chip
//              Temperature Sensor.
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments: This module uses the 48KHz clock generated by the 
//                      clock_top module 
//////////////////////////////////////////////////////////////////////////////////

module temp_sensor_top(
// Clock and Reset
input  wire        mclk,           // System clock
input  wire        en_clk,         // 48 KHz Enabling clock 
input  wire        puc_rst,        // Main system reset

// Peripheral Bus Interface 
input  wire [13:0] per_addr,       // Peripheral address
input  wire [15:0] per_din,        // Peripheral data input
input  wire        per_en,         // Peripheral enable (high active)
input  wire [ 1:0] per_we,         // Peripheral write enable (high active)
output wire [15:0] per_dout,       // Peripheral data output

// Temperature Sensor Interface
input  wire [11:0] temp_count_i,   // Sensor counter output
output reg       counter_rst_o,  // Sensor counter reset signal 
output wire        en_temp_ring_o, // Ring Osc. enable signal
output wire [ 3:0] switch_o        // Calibration switching output
    );

// LOCAL PARAMETERS -------------------------------------------------------------
parameter [14:0] BASE_ADDR = 15'h0080;  // Base address

// LOCAL WIRE/REG DECLARATIONS ---------------------------------------------------
reg  [11:0] count_reg;
reg  [2:0] count_r;
//(* keep = "true" *) wire en_clk_delayed;  // Only for FPGA
//wire        en_clk_delayed;

// CALIBRATION UNIT INSTANCE -----------------------------------------------------
calibration_unit calibration_unit_inst (
  .count_i(count_reg),
  .switch_o(switch_o)
);

// SENDING COUNT VALUE TO PROCESSOR ----------------------------------------------
// Local register selection
wire reg_sel = per_en & ~|per_we & (per_addr[13:0] == BASE_ADDR[14:1]);

always @(negedge en_clk or posedge puc_rst) begin
  if (puc_rst) begin
    count_reg <= 12'b0;
  end else begin
    count_reg <= temp_count_i;
  end
end

assign per_dout = (reg_sel == 1'b1) ? {4'b0, count_reg} : 16'b0; 

// COUNTER RESET GENERATION ------------------------------------------------------

always @(posedge mclk or posedge puc_rst) begin
if (puc_rst==1'b1)
counter_rst_o<=1'b0;
else
  if (en_clk==1'b1) begin
    count_r <= 3'b111;
    counter_rst_o <=1'b1;
  end else 
  begin
    count_r <= count_r - 3'b001;
    if(count_r ==3'b000)
      counter_rst_o<=1'b0;
  end
end

//logic to be changed
//assign en_clk_delayed = ~(~(~(~en_clk)));
//assign counter_rst_o  = ~(en_clk & (~en_clk_delayed));  //negated because resest to temperature sensor analog block is active low

// RING OSC. ENABLE --------------------------------------------------------------
assign en_temp_ring_o = ~puc_rst;

endmodule
